import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { provideRouter, Router } from '@angular/router';
import { vi } from 'vitest';
import { Login } from './login';
import { API_URL } from '../../core/api';
import { SesionService } from '../../core/services/sesion.service';
const USUARIO={id:1,nombre:'Demo',apellidos:null,correo:'demo@malvitec.com',rol:'cliente'};
describe('Login',()=>{
 let http:HttpTestingController;
 beforeEach(async()=>{localStorage.clear();await TestBed.configureTestingModule({imports:[Login],providers:[provideRouter([]),provideHttpClient(),provideHttpClientTesting()]}).compileComponents();http=TestBed.inject(HttpTestingController);});
 it('muestra errores al enviar vacío y el mensaje del backend si las credenciales no coinciden',async()=>{const f=TestBed.createComponent(Login);await f.componentInstance.submit();await f.whenStable();expect(f.nativeElement.textContent).toContain('Ingresa un correo electrónico válido.');http.expectNone(`${API_URL}/auth/login`);f.componentInstance.form.setValue({email:'demo@malvitec.com',password:'incorrecta'});const envio=f.componentInstance.submit();http.expectOne(`${API_URL}/auth/login`).flush({error:'Correo o contraseña incorrectos'},{status:401,statusText:'Unauthorized'});await envio;expect(f.componentInstance.error()).toContain('incorrectos');expect(TestBed.inject(SesionService).conectado()).toBe(false);});
 it('ingresa al inicio, guarda la sesión y borra la contraseña del formulario',async()=>{const c=TestBed.createComponent(Login).componentInstance;const nav=vi.spyOn(TestBed.inject(Router),'navigate').mockResolvedValue(true);c.form.setValue({email:'demo@malvitec.com',password:'Malvitec123!'});const envio=c.submit();const req=http.expectOne(`${API_URL}/auth/login`);expect(req.request.body).toEqual({correo:'demo@malvitec.com',contrasena:'Malvitec123!'});req.flush({token:'t',usuario:USUARIO});await envio;expect(nav).toHaveBeenCalledWith(['/home']);expect(c.form.controls.password.value).toBe('');expect(TestBed.inject(SesionService).usuario()?.nombre).toBe('Demo');});
 it('un proveedor entra a su panel',async()=>{const c=TestBed.createComponent(Login).componentInstance;const nav=vi.spyOn(TestBed.inject(Router),'navigate').mockResolvedValue(true);c.form.setValue({email:'techpower@malvitec.com',password:'Malvitec123!'});const envio=c.submit();http.expectOne(`${API_URL}/auth/login`).flush({token:'t',usuario:{...USUARIO,rol:'proveedor'}});await envio;expect(nav).toHaveBeenCalledWith(['/proveedor/dashboard']);});
 it('muestra y oculta la contraseña',async()=>{const f=TestBed.createComponent(Login);await f.whenStable();const button=f.nativeElement.querySelector('.password-row button') as HTMLButtonElement;button.click();await f.whenStable();expect(f.nativeElement.querySelector('#login-password').type).toBe('text');button.click();await f.whenStable();expect(f.nativeElement.querySelector('#login-password').type).toBe('password');});
 it('recupera la contraseña con el código',async()=>{const c=TestBed.createComponent(Login).componentInstance;await c.recover();expect(c.recoveryError()).toContain('código de 6 dígitos');c.recoveryForm.setValue({email:'demo@malvitec.com',code:'123456',password:'Nueva123!'});const envio=c.recover();const req=http.expectOne(`${API_URL}/auth/recuperar`);expect(req.request.body).toEqual({correo:'demo@malvitec.com',codigo:'123456',nueva_contrasena:'Nueva123!'});req.flush({mensaje:'ok'});await envio;expect(c.recovered()).toBe(true);});
});
